#include "pch.h"
/// @file KadEntry.cpp
/// @brief DHT data entry implementation.

#include "kademlia/KadEntry.h"
#include "kademlia/KadIO.h"
#include "kademlia/KadLog.h"
#include "kademlia/KadMiscUtils.h"
#include "utils/SafeFile.h"
#include "utils/TimeUtils.h"


namespace eMule::kad {

// Tag name constants matching MFC TAG_FILENAME / TAG_FILESIZE etc.
namespace {
const QByteArray kTagFilename = QByteArrayLiteral("\x01");
const QByteArray kTagFilesize = QByteArrayLiteral("\x02");
} // namespace

// ---------------------------------------------------------------------------
// Entry — public
// ---------------------------------------------------------------------------

Entry::Entry() = default;

Entry* Entry::copy() const
{
    auto* e = new Entry();
    e->m_address = m_address;
    e->m_tcpPort = m_tcpPort;
    e->m_udpPort = m_udpPort;
    e->m_keyID = m_keyID;
    e->m_sourceID = m_sourceID;
    e->m_size = m_size;
    e->m_lifetime = m_lifetime;
    e->m_source = m_source;
    e->m_fileNames = m_fileNames;
    e->m_tags = m_tags;
    return e;
}

namespace {

/// Does @p tag carry the name @p tagName?
///
/// Kad tag names are single bytes on the wire, and io::readKadTag normalizes
/// those to Tag::nameId() with an empty Tag::name(). Callers may hold either
/// shape, so match both — comparing only name() silently failed to find every
/// numeric-ID tag, which is nearly all of them.
[[nodiscard]] bool tagNameMatches(const Tag& tag, const QByteArray& tagName)
{
    if (tagName.size() == 1 && tag.name().isEmpty())
        return tag.nameId() == static_cast<uint8>(tagName[0]);
    return tag.name() == tagName;
}

} // namespace

QByteArray Entry::tagLookupKey(const Tag& tag)
{
    if (tag.name().isEmpty() && tag.nameId() != 0)
        return QByteArray(1, static_cast<char>(tag.nameId()));
    return tag.name();
}

uint64 Entry::getIntTagValue(const QByteArray& tagName, bool includeVirtual) const
{
    uint64 val = 0;
    getIntTagValue(tagName, val, includeVirtual);
    return val;
}

bool Entry::getIntTagValue(const QByteArray& tagName, uint64& outValue, bool includeVirtual) const
{
    // Check virtual tags first
    if (includeVirtual) {
        if (tagName == kTagFilesize) {
            outValue = m_size;
            return true;
        }
    }

    for (const auto& tag : m_tags) {
        if (tagNameMatches(tag, tagName) && tag.isInt64(true)) {
            outValue = tag.int64Value();
            return true;
        }
    }
    return false;
}

bool Entry::getFloatTagValue(const QByteArray& tagName, float& outValue) const
{
    for (const auto& tag : m_tags) {
        if (tagNameMatches(tag, tagName) && tag.isFloat()) {
            outValue = tag.floatValue();
            return true;
        }
    }
    return false;
}

QString Entry::getStrTagValue(const QByteArray& tagName) const
{
    if (tagName == kTagFilename)
        return getCommonFileName();

    for (const auto& tag : m_tags) {
        if (tagNameMatches(tag, tagName) && tag.isStr())
            return tag.strValue();
    }
    return {};
}

void Entry::addTag(Tag tag)
{
    // Some tags are generated by *us* when answering a search and must never be
    // accepted from a publisher — otherwise a spammer can forge its own trust
    // and publisher counts, which writeTagListWithPublishInfo() would then serve
    // alongside our genuine ones. MFC Entry.cpp:188-199.
    const QByteArray key = tagLookupKey(tag);
    if (key == QByteArrayLiteral(TAG_PUBLISHINFO)
        || key == QByteArrayLiteral(TAG_KADAICHHASHRESULT)) {
        logKad(QStringLiteral("Kad: filtered result-only tag received on publish"));
        return;
    }

    m_tags.push_back(std::move(tag));
}

uint32 Entry::getTagCount() const
{
    // Tag count includes virtual tags (filename, filesize)
    uint32 count = static_cast<uint32>(m_tags.size());
    if (!m_fileNames.empty())
        ++count; // filename
    if (m_size > 0)
        ++count; // filesize
    return count;
}

void Entry::writeTagList(FileDataIO& data) const
{
    writeTagListInc(data, 0);
}

QString Entry::getCommonFileName() const
{
    if (m_fileNames.empty())
        return {};

    // Return the filename with highest popularity
    const FileNameEntry* best = nullptr;
    for (const auto& entry : m_fileNames) {
        if (!best || entry.popularityIndex > best->popularityIndex)
            best = &entry;
    }
    return best ? best->fileName : QString();
}

QString Entry::getCommonFileNameLowerCase() const
{
    return kadTagStrToLower(getCommonFileName());
}

void Entry::setFileName(const QString& name)
{
    if (name.isEmpty())
        return;

    // Check if this filename already exists
    QString lower = kadTagStrToLower(name);
    for (auto& entry : m_fileNames) {
        if (kadTagStrToLower(entry.fileName) == lower) {
            ++entry.popularityIndex;
            return;
        }
    }

    // Add new filename
    m_fileNames.push_back({name, 1});
}

// ---------------------------------------------------------------------------
// Entry — protected
// ---------------------------------------------------------------------------

void Entry::writeTagListInc(FileDataIO& data, uint32 increaseTagNumber) const
{
    uint32 count = static_cast<uint32>(m_tags.size()) + increaseTagNumber;

    // Add virtual tags
    bool hasFilename = !m_fileNames.empty();
    bool hasFilesize = m_size > 0;
    if (hasFilename) ++count;
    if (hasFilesize) ++count;

    // MFC WriteTagList uses WriteByte — single uint8 for Kad tag count
    data.writeUInt8(static_cast<uint8>(count));

    // Write virtual filename tag
    if (hasFilename) {
        Tag fnTag(kTagFilename, getCommonFileName());
        io::writeKadTag(data, fnTag);
    }

    // Write virtual filesize tag
    if (hasFilesize) {
        if (m_size > 0xFFFFFFFF) {
            Tag fsTag(kTagFilesize, m_size);
            io::writeKadTag(data, fsTag);
        } else {
            Tag fsTag(kTagFilesize, static_cast<uint32>(m_size));
            io::writeKadTag(data, fsTag);
        }
    }

    // Write stored tags
    for (const auto& tag : m_tags)
        io::writeKadTag(data, tag);
}

// ---------------------------------------------------------------------------
// KeyEntry — public
// ---------------------------------------------------------------------------

std::unordered_map<uint32, uint32> KeyEntry::s_globalPublishIPs;

KeyEntry::KeyEntry() = default;

KeyEntry::~KeyEntry()
{
    if (m_publishingIPs) {
        // Decrease global tracking for each IP
        for (const auto& pip : *m_publishingIPs)
            adjustGlobalPublishTracking(pip.ip, false);
        delete m_publishingIPs;
    }
}

Entry* KeyEntry::copy() const
{
    auto* e = new KeyEntry();
    e->m_address = m_address;
    e->m_tcpPort = m_tcpPort;
    e->m_udpPort = m_udpPort;
    e->m_keyID = m_keyID;
    e->m_sourceID = m_sourceID;
    e->m_size = m_size;
    e->m_lifetime = m_lifetime;
    e->m_source = m_source;
    e->m_fileNames = m_fileNames;
    e->m_tags = m_tags;
    e->m_trustValue = m_trustValue;
    e->m_lastTrustValueCalc = m_lastTrustValueCalc;
    return e;
}

bool KeyEntry::startSearchTermsMatch(const SearchTerm& term)
{
    // Build search cache if needed
    if (m_searchTermCache.isEmpty()) {
        m_searchTermCache = getCommonFileNameLowerCase();
    }
    return searchTermsMatch(term);
}

void KeyEntry::mergeIPsAndFilenames(KeyEntry* from)
{
    // Called on the *new* entry when it replaces a stored one, with the old
    // entry (or nullptr for a first publish) as `from`. The new entry takes over
    // the old one's publisher list, AICH hashes and alternative file names;
    // everything else keeps the refreshed values. MFC Entry.cpp:343-469.
    //
    // Note the direction: this port previously merged the other way round (old
    // absorbing new) and then dropped the new entry on the floor without taking
    // ownership, leaking one KeyEntry per refresh publish and never updating the
    // stored entry's tags, size or lifetime.
    if (m_publishingIPs != nullptr)
        return; // already merged — this instance must be a fresh entry

    // Take the AICH hash this publish reported, if any, out of the way; it is
    // re-added below once we know whether this is a refresh.
    QByteArray newAICHHash;
    if (!m_aichHashes.empty()) {
        newAICHHash = m_aichHashes.front();
        m_aichHashes.clear();
        m_aichHashPopularity.clear();
    }

    bool refresh = false;
    bool fastRefresh = false;

    if (from == nullptr || from->m_publishingIPs == nullptr) {
        // Brand new entry — start the tracking list.
        m_publishingIPs = new std::list<PublishingIP>();
    } else {
        m_aichHashes = from->m_aichHashes;
        m_aichHashPopularity = from->m_aichHashPopularity;

        // Adopt the old publisher list wholesale.
        m_publishingIPs = from->m_publishingIPs;
        from->m_publishingIPs = nullptr;

        for (auto it = m_publishingIPs->begin(); it != m_publishingIPs->end(); ++it) {
            if (it->ip != m_address)
                continue;

            refresh = true;
            PublishingIP cur = *it;
            const time_t now = time(nullptr);
            // Republishing sooner than expected does not count towards filename
            // popularity, so a spammer cannot promote its own name by looping.
            //
            // NB: MFC's condition here is mis-parenthesised —
            // `(tNow < Cur.m_tLastPublish) + (KADEMLIAREPUBLISHTIMES - HR2S(1))`
            // adds a bool to a constant and is therefore always true. We port the
            // evident intent instead.
            if (now < cur.lastPublish + (KADEMLIAREPUBLISHTIMES - HR2S(1)))
                fastRefresh = true;
            cur.lastPublish = now;

            // Track any change in the AICH hash this publisher reports.
            if (!newAICHHash.isEmpty()) {
                if (cur.aichHashIdx == kNoAICHHash) {
                    cur.aichHashIdx = addRemoveAICHHash(newAICHHash, true);
                } else if (cur.aichHashIdx < m_aichHashes.size()
                           && m_aichHashes[cur.aichHashIdx] != newAICHHash) {
                    addRemoveAICHHash(m_aichHashes[cur.aichHashIdx], false);
                    cur.aichHashIdx = addRemoveAICHHash(newAICHHash, true);
                }
            } else if (cur.aichHashIdx != kNoAICHHash
                       && cur.aichHashIdx < m_aichHashes.size()) {
                addRemoveAICHHash(m_aichHashes[cur.aichHashIdx], false);
                cur.aichHashIdx = kNoAICHHash;
            }

            // Move this publisher to the back — the list is oldest-first, which
            // is what the 100-entry cap below relies on.
            m_publishingIPs->erase(it);
            m_publishingIPs->push_back(cur);
            break;
        }

        // Keep the old trust value in case we do not recalculate below.
        m_trustValue = from->m_trustValue;
        m_lastTrustValueCalc = from->m_lastTrustValueCalc;

        // Carry over the alternative file names. This entry has exactly one name
        // (it came from a single publisher); if the old entry already knew it,
        // bump that name's popularity instead of duplicating it.
        FileNameEntry currentName;
        if (!m_fileNames.empty()) {
            currentName = m_fileNames.front();
            m_fileNames.clear();
        }
        bool duplicate = false;
        for (const auto& nameToCopy : from->m_fileNames) {
            FileNameEntry copy = nameToCopy;
            if (kadTagStrToLower(currentName.fileName) == kadTagStrToLower(copy.fileName)) {
                duplicate = true;
                copy.popularityIndex += fastRefresh ? 0u : 1u;
            }
            m_fileNames.push_back(copy);
        }
        if (!duplicate && !currentName.fileName.isEmpty())
            m_fileNames.push_back(currentName);
    }

    if (refresh)
        return; // a refresh changes no publisher counts

    // A publisher we have not seen before for this entry: record it. This is
    // what the whole trust system is built on, and what was missing — nothing
    // ever populated m_publishingIPs, so getTrustValue() was permanently 0 and
    // the trusted-first result ordering never ranked anything.
    PublishingIP add;
    add.lastPublish = time(nullptr);
    add.ip = m_address;
    add.aichHashIdx = newAICHHash.isEmpty() ? kNoAICHHash
                                            : addRemoveAICHHash(newAICHHash, true);
    m_publishingIPs->push_back(add);
    adjustGlobalPublishTracking(add.ip, true);

    // Cap at 100 publishers so calculation/storage stays bounded; drop the
    // oldest, releasing its AICH reference and tracking count.
    if (m_publishingIPs->size() > 100) {
        PublishingIP oldest = m_publishingIPs->front();
        m_publishingIPs->pop_front();
        if (oldest.aichHashIdx != kNoAICHHash && oldest.aichHashIdx < m_aichHashes.size())
            addRemoveAICHHash(m_aichHashes[oldest.aichHashIdx], false);
        adjustGlobalPublishTracking(oldest.ip, false);
    }

    recalculateTrustValue();
}

void KeyEntry::cleanUpTrackedPublishers()
{
    if (!m_publishingIPs)
        return;

    time_t now = time(nullptr);
    constexpr time_t kExpireTime = 60 * 60 * 48; // 48 hours

    auto it = m_publishingIPs->begin();
    while (it != m_publishingIPs->end()) {
        if ((now - it->lastPublish) > kExpireTime) {
            adjustGlobalPublishTracking(it->ip, false);
            it = m_publishingIPs->erase(it);
        } else {
            ++it;
        }
    }
}

float KeyEntry::getTrustValue()
{
    // Recalculate if stale (every 10 minutes)
    uint32 now = static_cast<uint32>(time(nullptr));
    if (m_trustValue == 0.0f || (now - m_lastTrustValueCalc) > 600) {
        recalculateTrustValue();
        m_lastTrustValueCalc = now;
    }
    return m_trustValue;
}

void KeyEntry::writePublishTrackingDataToFile(FileDataIO& data)
{
    if (!m_publishingIPs || m_publishingIPs->empty()) {
        data.writeUInt32(0);
        return;
    }

    data.writeUInt32(static_cast<uint32>(m_publishingIPs->size()));
    for (const auto& pip : *m_publishingIPs) {
        data.writeUInt32(pip.ip.toUint32());
        data.writeUInt32(static_cast<uint32>(pip.lastPublish));
        // AICH hash index (v9+)
        data.writeUInt16(pip.aichHashIdx);
    }

    // Write AICH hashes
    data.writeUInt8(static_cast<uint8>(m_aichHashes.size()));
    for (const auto& hash : m_aichHashes) {
        data.write(hash.constData(), 20);
    }
}

void KeyEntry::readPublishTrackingDataFromFile(FileDataIO& data, bool includesAICH)
{
    uint32 count = data.readUInt32();
    if (count == 0)
        return;

    if (!m_publishingIPs)
        m_publishingIPs = new std::list<PublishingIP>();

    for (uint32 i = 0; i < count; ++i) {
        PublishingIP pip;
        pip.ip = Address::fromHostOrder(data.readUInt32());
        pip.lastPublish = static_cast<time_t>(data.readUInt32());
        if (includesAICH)
            pip.aichHashIdx = data.readUInt16();
        m_publishingIPs->push_back(pip);
        adjustGlobalPublishTracking(pip.ip, true);
    }

    if (includesAICH) {
        uint8 aichCount = data.readUInt8();
        m_aichHashes.resize(aichCount);
        for (uint8 i = 0; i < aichCount; ++i) {
            m_aichHashes[i].resize(20);
            data.read(m_aichHashes[i].data(), 20);
        }
    }
}

void KeyEntry::dirtyDeletePublishData()
{
    // Delete without adjusting global tracking (for mass cleanup)
    delete m_publishingIPs;
    m_publishingIPs = nullptr;
    m_aichHashes.clear();
    m_aichHashPopularity.clear();
}

void KeyEntry::writeTagListWithPublishInfo(FileDataIO& data)
{
    // MFC WriteTagListWithPublishInfo: adds TAG_PUBLISHINFO + optional TAG_KADAICHHASHRESULT
    uint32 nAdditionalTags = 1 + static_cast<uint32>(!m_aichHashes.empty());
    writeTagListInc(data, nAdditionalTags);

    // TAG_PUBLISHINFO (0x33): packed uint32 = (nameCount<<24)|(publishers<<16)|(trust*100)
    uint32 trust = static_cast<uint32>(static_cast<uint16>(getTrustValue() * 100.0f));
    uint32 publishers = m_publishingIPs
        ? static_cast<uint32>(m_publishingIPs->size() % 256) : 0;
    uint32 names = static_cast<uint32>(m_fileNames.size() % 256);
    uint32 tagValue = (names << 24) | (publishers << 16) | trust;
    Tag publishTag(QByteArrayLiteral(TAG_PUBLISHINFO), tagValue);
    io::writeKadTag(data, publishTag);

    // TAG_KADAICHHASHRESULT (0x37): BSOB with popularity + hash pairs
    if (!m_aichHashes.empty()) {
        SafeMemFile aichBuf;
        uint8 count = 0;
        // Count hashes with popularity > 0, limit to ~12 (255 byte BSOB limit)
        for (size_t i = 0; i < m_aichHashes.size(); ++i) {
            if (i < m_aichHashPopularity.size() && m_aichHashPopularity[i] > 0) {
                ++count;
                // 1 + (hashSize * (count+1)) + (1 * (count+1)) > 250 → truncate
                if (1 + (m_aichHashes[i].size() * (count + 1)) + (count + 1) > 250)
                    break;
            }
        }
        aichBuf.writeUInt8(count);
        uint8 written = 0;
        for (size_t i = 0; written < count && i < m_aichHashes.size(); ++i) {
            if (i < m_aichHashPopularity.size() && m_aichHashPopularity[i] > 0) {
                aichBuf.writeUInt8(m_aichHashPopularity[i]);
                aichBuf.write(m_aichHashes[i].constData(), m_aichHashes[i].size());
                ++written;
            }
        }
        QByteArray bsob = aichBuf.buffer().left(static_cast<qsizetype>(aichBuf.length()));
        io::writeKadTagBsob(data, QByteArrayLiteral(TAG_KADAICHHASHRESULT), bsob);
    }
}

void KeyEntry::resetGlobalTrackingMap()
{
    s_globalPublishIPs.clear();
}

// ---------------------------------------------------------------------------
// KeyEntry — private
// ---------------------------------------------------------------------------

bool KeyEntry::searchTermsMatch(const SearchTerm& term) const
{
    switch (term.type) {
    case SearchTerm::Type::AND:
        return (term.left && searchTermsMatch(*term.left))
               && (term.right && searchTermsMatch(*term.right));

    case SearchTerm::Type::OR:
        return (term.left && searchTermsMatch(*term.left))
               || (term.right && searchTermsMatch(*term.right));

    case SearchTerm::Type::NOT:
        return (term.left && searchTermsMatch(*term.left))
               && !(term.right && searchTermsMatch(*term.right));

    case SearchTerm::Type::String:
        // A string term holds several words ("aaa bbb ccc") and is matched as
        // "aaa AND bbb AND ccc" — ALL must be present. Matching ANY made this
        // node serve massive false positives for multi-word searches.
        // MFC Entry.cpp:242-255.
        if (term.strings.empty())
            return false;
        for (const auto& word : term.strings) {
            if (!m_searchTermCache.contains(word, Qt::CaseInsensitive))
                return false;
        }
        return true;

    case SearchTerm::Type::MetaTag: {
        if (!term.tag.isStr())
            return false;
        const QByteArray key = tagLookupKey(term.tag);
        // TAG_FILEFORMAT is never published separately — it is part of the file
        // name, so match it against the extension. MFC Entry.cpp:258-265.
        if (key == QByteArrayLiteral(TAG_FILEFORMAT)) {
            const QString name = getCommonFileNameLowerCase();
            const qsizetype dot = name.lastIndexOf(QLatin1Char('.'));
            if (dot < 0)
                return false;
            return name.mid(dot + 1).compare(term.tag.strValue(), Qt::CaseInsensitive) == 0;
        }
        // Other string metatags match on full-string case-insensitive equality
        // (MFC EqualKadTagStr, DataIO.cpp:518), not substring — `contains` served
        // false positives (e.g. artist "foo" matching "foobar").
        return getStrTagValue(key).compare(term.tag.strValue(), Qt::CaseInsensitive) == 0;
    }

    case SearchTerm::Type::OpGreaterEqual:
    case SearchTerm::Type::OpLessEqual:
    case SearchTerm::Type::OpGreater:
    case SearchTerm::Type::OpLess:
    case SearchTerm::Type::OpEqual:
    case SearchTerm::Type::OpNotEqual: {
        // A float search tag compares against a stored float tag; MFC has a
        // dedicated float branch (Entry.cpp:296-319). Integer tags take the
        // path below. Forcing a float through the integer path gave wrong results.
        if (term.tag.isFloat()) {
            float entryVal = 0.0f;
            if (!getFloatTagValue(tagLookupKey(term.tag), entryVal))
                return false;
            const float searchVal = term.tag.floatValue();
            switch (term.type) {
            case SearchTerm::Type::OpGreaterEqual: return entryVal >= searchVal;
            case SearchTerm::Type::OpLessEqual:    return entryVal <= searchVal;
            case SearchTerm::Type::OpGreater:      return entryVal > searchVal;
            case SearchTerm::Type::OpLess:         return entryVal < searchVal;
            case SearchTerm::Type::OpEqual:        return entryVal == searchVal;
            case SearchTerm::Type::OpNotEqual:     return entryVal != searchVal;
            default: return false;
            }
        }
        uint64 entryVal = 0;
        if (!getIntTagValue(tagLookupKey(term.tag), entryVal, true))
            return false;
        uint64 searchVal = term.tag.int64Value();
        switch (term.type) {
        case SearchTerm::Type::OpGreaterEqual: return entryVal >= searchVal;
        case SearchTerm::Type::OpLessEqual:    return entryVal <= searchVal;
        case SearchTerm::Type::OpGreater:      return entryVal > searchVal;
        case SearchTerm::Type::OpLess:         return entryVal < searchVal;
        case SearchTerm::Type::OpEqual:        return entryVal == searchVal;
        case SearchTerm::Type::OpNotEqual:     return entryVal != searchVal;
        default: return false;
        }
    }
    }
    return false;
}

void KeyEntry::recalculateTrustValue()
{
    // An indicator of how trustworthy (vs. spammy) this entry is. Each publisher
    // contributes points, but the points for a /24 block are shared out among
    // every entry that block published — so one honest publisher scores the full
    // 10, while a spammer flooding many entries from one network dilutes its own
    // contribution towards zero. Callers treat >= 1.0 as trusted.
    // MFC Entry.cpp:471-505.
    constexpr float kPublishPointsPerSubnet = 10.0f;

    // NB: the staleness stamp is owned by getTrustValue(), which keeps it in
    // time(nullptr) seconds — do not set it here from a tick counter.
    m_trustValue = 0.0f;

    if (!m_publishingIPs)
        return;

    for (const auto& pip : *m_publishingIPs) {
        auto it = s_globalPublishIPs.find(pip.ip.toUint32() & ~0xFFu);
        if (it != s_globalPublishIPs.end() && it->second > 0)
            m_trustValue += kPublishPointsPerSubnet / static_cast<float>(it->second);
    }
}

void KeyEntry::adjustGlobalPublishTracking(const Address& ip, bool increase)
{
    // Keyed by /24 block, not by exact IP — see s_globalPublishIPs.
    const uint32 subnet = ip.toUint32() & ~0xFFu;
    if (increase) {
        ++s_globalPublishIPs[subnet];
    } else {
        auto it = s_globalPublishIPs.find(subnet);
        if (it != s_globalPublishIPs.end()) {
            if (it->second <= 1)
                s_globalPublishIPs.erase(it);
            else
                --it->second;
        }
    }
}

uint16 KeyEntry::addRemoveAICHHash(const QByteArray& hash, bool add)
{
    for (std::size_t i = 0; i < m_aichHashes.size(); ++i) {
        if (m_aichHashes[i] != hash)
            continue;
        if (add) {
            ++m_aichHashPopularity[i];
        } else if (m_aichHashPopularity[i] > 0) {
            --m_aichHashPopularity[i];
        }
        return static_cast<uint16>(i);
    }

    if (!add)
        return kNoAICHHash;

    m_aichHashes.push_back(hash);
    m_aichHashPopularity.push_back(1);
    return static_cast<uint16>(m_aichHashes.size() - 1);
}

} // namespace eMule::kad
