/// @file tst_UsenetReleaseChecks.cpp
/// @brief The SFV check and the unwanted-file classifier, without a queue.
///
/// Both are pure functions over names and files, so every edge worth having is
/// cheaper here than through a posted release. tst_UsenetPostPipeline covers the
/// wiring; this covers the judgement — and mostly what must *not* be judged: a
/// sample nobody posted is not damage, and a software release is supposed to
/// carry executables.

#include "TestHelpers.h"

#include "decode/YencDecoder.h"
#include "post/UsenetReleaseChecks.h"
#include "queue/UsenetQueueItem.h"
#include "queue/UsenetRepairEstimate.h"

#include <QDir>
#include <QFile>
#include <QTest>

using namespace eMule::usenet;
using eMule::testing::TempDir;

namespace {

/// @p parts articles of @p bytes each, by the NZB's account.
NzbFileInfo nzbFile(const QString& name, int parts, qint64 bytes = 4200)
{
    NzbFileInfo info;
    info.subject = name;
    info.fileName = name;
    for (int p = 1; p <= parts; ++p)
        info.segments.append({QStringLiteral("%1.%2@test").arg(name).arg(p), bytes, p});
    return info;
}

/// @p missing parts resolved as holes, @p pending not resolved yet, the rest
/// arrived at @p partSize decoded bytes each.
UsenetFileState fileState(int parts, const QList<int>& missing, const QList<int>& pending = {},
                          qint64 partSize = 3000)
{
    UsenetFileState st;
    st.done.resize(parts);
    st.missing.resize(parts);
    for (int p = 1; p <= parts; ++p) {
        if (pending.contains(p))
            continue;
        st.done.setBit(p - 1);
        if (missing.contains(p)) {
            st.missing.setBit(p - 1);
            ++st.missingSegments;
        } else {
            st.decodedBytes += partSize;
        }
    }
    return st;
}

void addFile(UsenetQueueItem& item, const NzbFileInfo& info, const UsenetFileState& st)
{
    item.nzb.files.append(info);
    item.files.append(st);
}

QList<int> parts(int from, int to)
{
    QList<int> out;
    for (int p = from; p <= to; ++p)
        out.append(p);
    return out;
}

/// The recovery set of these cases: one 24 000-byte archive, 4 000-byte blocks.
const QList<Par2SetFile> kRelSet = [] {
    Par2SetFile f;
    f.fileName = QStringLiteral("Rel.zip");
    f.size = 24000;
    return QList<Par2SetFile>{f};
}();

constexpr qint64 kBlock = 4000;

/// The index, sealed, and a recovery volume nobody has asked for yet.
void addPar2(UsenetQueueItem& item, const QString& volumeName, int volumeParts)
{
    addFile(item, nzbFile(QStringLiteral("Rel.par2"), 1), fileState(1, {}, {}, 2000));
    addFile(item, nzbFile(volumeName, volumeParts), fileState(volumeParts, {}, parts(1, volumeParts)));
}

bool writeFile(const QString& path, const QByteArray& data)
{
    QFile f(path);
    return f.open(QIODevice::WriteOnly) && f.write(data) == data.size();
}

QByteArray sfvLine(const QString& name, const QByteArray& content)
{
    return QStringLiteral("%1 %2\r\n")
        .arg(name)
        .arg(yencCrc32(0, content), 8, 16, QLatin1Char('0'))
        .toUtf8();
}

const QStringList kExtensions = parseExtensionList(QStringLiteral(
    "exe, com, scr, pif, lnk, bat, cmd, vbs, vbe, js, jse, wsf, hta, cpl, msi, ps1, jar, reg"));

} // namespace

class tst_UsenetReleaseChecks : public QObject {
    Q_OBJECT

private slots:
    void sfvParsingHandlesCommentsSpacesPathsAndCase();
    void aCleanSetPassesWhateverCaseTheSfvUses();
    void aDamagedFileIsNamed();
    void anExpectedFileThatIsMissingIsDamage();
    void aListedSampleNobodyPostedIsNotDamage();
    void anSfvListingNothingPresentChecksNothing();
    void noSfvMeansNoOpinion();
    void cancellingStopsTheCheck();
    void extensionListsAreNormalised();
    void videoTagsMakeAMediaRelease();
    void anExecutableInAMediaReleaseIsUnwanted();
    void anExecutableInASoftwareReleaseIsNot();
    void aDoubleExtensionIsUnwantedEvenWithoutMedia();
    void anEmptyListTurnsTheCheckOff();
    void aFakeMkvIsUnwantedAndAMislabelledOneIsNot();
    void fileListsNameThreeAndCountTheRest();
    void aHoleTheRecoverySetCoversIsRepairable();
    void losingMoreThanTheSetHoldsIsUnrepairable();
    void aFileStillDownloadingClaimsNoDamage();
    void aRepostCountsOnlyItsBestCopy();
    void aRepeatedPartNumberIsNotAHole();
    void recoveryDataIsCountedWhateverItIsCalled();
    void nothingToJudgeFromIsUnknown();
};

void tst_UsenetReleaseChecks::sfvParsingHandlesCommentsSpacesPathsAndCase()
{
    const QByteArray text = "; generated by QuickSFV\r\n"
                            "\r\n"
                            "movie.part01.rar 1A2B3C4D\r\n"
                            "My Movie (2024).mkv\tdeadbeef\n"
                            "sub\\dir\\Sample.MKV 00000000\n"
                            "\"quoted name.nfo\" 0badf00d\n"
                            "../../etc/passwd 12345678\n"
                            "a line with no checksum\n"
                            "short.bin 1234\n";

    const QList<SfvEntry> entries = parseSfv(text);
    QCOMPARE(entries.size(), 5);
    QCOMPARE(entries.at(0).fileName, QStringLiteral("movie.part01.rar"));
    QCOMPARE(entries.at(0).crc, 0x1A2B3C4Du);
    QCOMPARE(entries.at(1).fileName, QStringLiteral("My Movie (2024).mkv"));
    QCOMPARE(entries.at(1).crc, 0xDEADBEEFu);
    // A path is never kept: the file is looked up beside the .sfv and nowhere else.
    QCOMPARE(entries.at(2).fileName, QStringLiteral("Sample.MKV"));
    QCOMPARE(entries.at(3).fileName, QStringLiteral("quoted name.nfo"));
    QCOMPARE(entries.at(4).fileName, QStringLiteral("passwd"));
}

void tst_UsenetReleaseChecks::aCleanSetPassesWhateverCaseTheSfvUses()
{
    TempDir tmp;
    const QByteArray a = eMule::testing::randomBytes(70000);
    const QByteArray b = eMule::testing::randomBytes(3000);
    QVERIFY(writeFile(tmp.filePath(QStringLiteral("rel.r00")), a));
    QVERIFY(writeFile(tmp.filePath(QStringLiteral("rel.rar")), b));
    QVERIFY(writeFile(tmp.filePath(QStringLiteral("rel.sfv")),
                      sfvLine(QStringLiteral("REL.R00"), a) + sfvLine(QStringLiteral("rel.rar"), b)));

    const SfvCheck check = verifySfv(tmp.path(), {QStringLiteral("rel.r00"),
                                                  QStringLiteral("rel.rar"),
                                                  QStringLiteral("rel.sfv")});
    QCOMPARE(check.outcome, SfvCheck::Outcome::Clean);
    QCOMPARE(check.checked, 2);
    QVERIFY(check.damaged.isEmpty());
    QCOMPARE(check.sfvFiles, QStringList{tmp.filePath(QStringLiteral("rel.sfv"))});
}

void tst_UsenetReleaseChecks::aDamagedFileIsNamed()
{
    TempDir tmp;
    QByteArray a = eMule::testing::randomBytes(5000);
    QVERIFY(writeFile(tmp.filePath(QStringLiteral("rel.sfv")), sfvLine(QStringLiteral("rel.rar"), a)));
    a[2500] = char(~quint8(a.at(2500)));
    QVERIFY(writeFile(tmp.filePath(QStringLiteral("rel.rar")), a));

    const SfvCheck check = verifySfv(tmp.path(), {QStringLiteral("rel.rar")});
    QCOMPARE(check.outcome, SfvCheck::Outcome::Damaged);
    QCOMPARE(check.damaged, QStringList{QStringLiteral("rel.rar")});
}

void tst_UsenetReleaseChecks::anExpectedFileThatIsMissingIsDamage()
{
    TempDir tmp;
    const QByteArray a = eMule::testing::randomBytes(4000);
    QVERIFY(writeFile(tmp.filePath(QStringLiteral("rel.rar")), a));
    QVERIFY(writeFile(tmp.filePath(QStringLiteral("rel.sfv")),
                      sfvLine(QStringLiteral("rel.rar"), a) + sfvLine(QStringLiteral("rel.r00"), a)));

    // The download delivered rel.r00 and it is gone: that is not a sample.
    const SfvCheck check = verifySfv(tmp.path(), {QStringLiteral("rel.rar"),
                                                  QStringLiteral("rel.r00")});
    QCOMPARE(check.outcome, SfvCheck::Outcome::Damaged);
    QCOMPARE(check.damaged, QStringList{QStringLiteral("rel.r00")});
}

void tst_UsenetReleaseChecks::aListedSampleNobodyPostedIsNotDamage()
{
    TempDir tmp;
    const QByteArray a = eMule::testing::randomBytes(4000);
    QVERIFY(writeFile(tmp.filePath(QStringLiteral("movie.mkv")), a));
    QVERIFY(writeFile(tmp.filePath(QStringLiteral("rel.sfv")),
                      sfvLine(QStringLiteral("movie.mkv"), a)
                          + sfvLine(QStringLiteral("sample.mkv"), a)));

    const SfvCheck check = verifySfv(tmp.path(), {QStringLiteral("movie.mkv")});
    QCOMPARE(check.outcome, SfvCheck::Outcome::Clean);
    QCOMPARE(check.unposted, QStringList{QStringLiteral("sample.mkv")});
}

void tst_UsenetReleaseChecks::anSfvListingNothingPresentChecksNothing()
{
    TempDir tmp;
    QVERIFY(writeFile(tmp.filePath(QStringLiteral("movie.mkv")), "data"));
    QVERIFY(writeFile(tmp.filePath(QStringLiteral("other.sfv")),
                      sfvLine(QStringLiteral("unrelated.bin"), "x")));

    const SfvCheck check = verifySfv(tmp.path(), {QStringLiteral("movie.mkv")});
    QCOMPARE(check.outcome, SfvCheck::Outcome::NothingToCheck);
    QCOMPARE(check.checked, 0);
}

void tst_UsenetReleaseChecks::noSfvMeansNoOpinion()
{
    TempDir tmp;
    QVERIFY(writeFile(tmp.filePath(QStringLiteral("movie.mkv")), "data"));
    QCOMPARE(verifySfv(tmp.path(), {QStringLiteral("movie.mkv")}).outcome,
             SfvCheck::Outcome::NoSfv);
}

void tst_UsenetReleaseChecks::cancellingStopsTheCheck()
{
    TempDir tmp;
    const QByteArray a = eMule::testing::randomBytes(4000);
    QVERIFY(writeFile(tmp.filePath(QStringLiteral("rel.rar")), a));
    QVERIFY(writeFile(tmp.filePath(QStringLiteral("rel.sfv")), sfvLine(QStringLiteral("rel.rar"), a)));

    const SfvCheck check = verifySfv(tmp.path(), {QStringLiteral("rel.rar")}, {},
                                     [] { return true; });
    QCOMPARE(check.outcome, SfvCheck::Outcome::Cancelled);
}

void tst_UsenetReleaseChecks::extensionListsAreNormalised()
{
    QCOMPARE(parseExtensionList(QStringLiteral(" .EXE, com;*.scr  bat,exe")),
             QStringList({QStringLiteral("exe"), QStringLiteral("com"), QStringLiteral("scr"),
                          QStringLiteral("bat")}));
    QVERIFY(parseExtensionList(QStringLiteral("  , ; ")).isEmpty());
}

void tst_UsenetReleaseChecks::videoTagsMakeAMediaRelease()
{
    QVERIFY(looksLikeVideoReleaseName(QStringLiteral("Some.Movie.2024.1080p.WEB-DL.x264-GRP")));
    QVERIFY(looksLikeVideoReleaseName(QStringLiteral("Show.S01E02.720p.HDTV")));
    QVERIFY(looksLikeVideoReleaseName(QStringLiteral("Film 2160p BluRay REMUX")));
    QVERIFY(looksLikeVideoReleaseName(QStringLiteral("old.film.h.264")));

    // Software carries version numbers and architectures, not video tags.
    QVERIFY(!looksLikeVideoReleaseName(QStringLiteral("Ubuntu 24.04 LTS Desktop amd64")));
    QVERIFY(!looksLikeVideoReleaseName(QStringLiteral("Photoshop.2024.v25.x64")));
    QVERIFY(!looksLikeVideoReleaseName(QStringLiteral("Setup1080p")));
}

void tst_UsenetReleaseChecks::anExecutableInAMediaReleaseIsUnwanted()
{
    // The media is among the names themselves...
    QCOMPARE(unwantedFileNames({QStringLiteral("Movie.mkv"), QStringLiteral("dir/Codec Pack.exe"),
                                QStringLiteral("readme.txt")},
                               kExtensions, /*mediaRelease*/ false),
             QStringList{QStringLiteral("Codec Pack.exe")});

    // ...or already known from the release: the fake that ships no video at all.
    QCOMPARE(unwantedFileNames({QStringLiteral("setup.exe"), QStringLiteral("password.txt")},
                               kExtensions, /*mediaRelease*/ true),
             QStringList{QStringLiteral("setup.exe")});
}

void tst_UsenetReleaseChecks::anExecutableInASoftwareReleaseIsNot()
{
    QVERIFY(unwantedFileNames({QStringLiteral("setup.exe"), QStringLiteral("data1.cab"),
                               QStringLiteral("install.bat"), QStringLiteral("readme.txt")},
                              kExtensions, /*mediaRelease*/ false)
                .isEmpty());
}

void tst_UsenetReleaseChecks::aDoubleExtensionIsUnwantedEvenWithoutMedia()
{
    QCOMPARE(unwantedFileNames({QStringLiteral("Movie.2024.mkv.exe"), QStringLiteral("tool.tar.exe")},
                               kExtensions, /*mediaRelease*/ false),
             QStringList{QStringLiteral("Movie.2024.mkv.exe")});
}

void tst_UsenetReleaseChecks::anEmptyListTurnsTheCheckOff()
{
    QVERIFY(unwantedFileNames({QStringLiteral("Movie.mkv"), QStringLiteral("Movie.mkv.exe")}, {},
                              /*mediaRelease*/ true)
                .isEmpty());
}

void tst_UsenetReleaseChecks::aFakeMkvIsUnwantedAndAMislabelledOneIsNot()
{
    TempDir tmp;
    QByteArray exe("MZ\x90\x00\x03\x00\x00\x00\x04\x00\x00\x00\xff\xff", 14);
    exe += QByteArray(4096, '\0');
    QVERIFY(writeFile(tmp.filePath(QStringLiteral("fake.mkv")), exe));

    QByteArray matroska("\x1a\x45\xdf\xa3\x9f\x42\x86\x81\x01\x42\xf7\x81", 12);
    matroska += QByteArray(4096, '\0');
    QVERIFY(writeFile(tmp.filePath(QStringLiteral("real.mkv")), matroska));

    // An MP4 named .mkv is the wrong label on a real video: it plays.
    QByteArray mp4("\x00\x00\x00\x18" "ftypmp42", 12);
    mp4 += QByteArray(4096, '\0');
    QVERIFY(writeFile(tmp.filePath(QStringLiteral("mislabelled.mkv")), mp4));

    QVERIFY(writeFile(tmp.filePath(QStringLiteral("notes.txt")), exe));

    // Bytes no sniffer recognises may still be a real, unusual video.
    QVERIFY(writeFile(tmp.filePath(QStringLiteral("unknown.mkv")),
                      QByteArray("\x10\x20\x30\x40", 4) + QByteArray(4096, '\x55')));

    QVERIFY(isFakeMediaFile(tmp.filePath(QStringLiteral("fake.mkv"))));
    QVERIFY(!isFakeMediaFile(tmp.filePath(QStringLiteral("real.mkv"))));
    QVERIFY(!isFakeMediaFile(tmp.filePath(QStringLiteral("mislabelled.mkv"))));
    QVERIFY(!isFakeMediaFile(tmp.filePath(QStringLiteral("notes.txt"))));
    QVERIFY(!isFakeMediaFile(tmp.filePath(QStringLiteral("unknown.mkv"))));
}

void tst_UsenetReleaseChecks::fileListsNameThreeAndCountTheRest()
{
    QCOMPARE(describeFileList({QStringLiteral("a")}), QStringLiteral("a"));
    QCOMPARE(describeFileList({QStringLiteral("a"), QStringLiteral("b"), QStringLiteral("c")}),
             QStringLiteral("a, b, c"));
    QCOMPARE(describeFileList({QStringLiteral("a"), QStringLiteral("b"), QStringLiteral("c"),
                               QStringLiteral("d"), QStringLiteral("e")}),
             QStringLiteral("a, b, c and 2 more"));
}

// -- The repair estimate --------------------------------------------------------
//
// Every case is about the direction of the error. Stopping a release that would
// have repaired is the failure that costs the user something; letting a hopeless
// one run on is merely today's behaviour.

void tst_UsenetReleaseChecks::aHoleTheRecoverySetCoversIsRepairable()
{
    UsenetQueueItem item;
    addFile(item, nzbFile(QStringLiteral("Rel.zip"), 8), fileState(8, {3}));
    addPar2(item, QStringLiteral("Rel.vol0+8.par2"), 8);

    const UsenetRepairEstimate e = estimateRepair(item, kBlock, kRelSet);
    QCOMPARE(e.verdict, UsenetRepairEstimate::Verdict::Repairable);
    QCOMPARE(e.damagedBlocks, qint64(1));
    QVERIFY(e.recoveryBlocks >= 8);
}

void tst_UsenetReleaseChecks::losingMoreThanTheSetHoldsIsUnrepairable()
{
    UsenetQueueItem item;
    addFile(item, nzbFile(QStringLiteral("Rel.zip"), 8), fileState(8, parts(1, 6)));
    addPar2(item, QStringLiteral("Rel.vol0+2.par2"), 2);

    // 18 000 bytes short needs at least 5 blocks; index and volume hold at most 3.
    const UsenetRepairEstimate e = estimateRepair(item, kBlock, kRelSet);
    QCOMPARE(e.verdict, UsenetRepairEstimate::Verdict::Unrepairable);
    QCOMPARE(e.damagedBlocks, qint64(5));
    QCOMPARE(e.recoveryBlocks, qint64(3));
}

void tst_UsenetReleaseChecks::aFileStillDownloadingClaimsNoDamage()
{
    UsenetQueueItem item;
    addFile(item, nzbFile(QStringLiteral("Rel.zip"), 8), fileState(8, parts(1, 6), {8}));
    addPar2(item, QStringLiteral("Rel.vol0+2.par2"), 2);

    const UsenetRepairEstimate e = estimateRepair(item, kBlock, kRelSet);
    QCOMPARE(e.verdict, UsenetRepairEstimate::Verdict::Repairable);
    QCOMPARE(e.damagedBlocks, qint64(0));
}

void tst_UsenetReleaseChecks::aRepostCountsOnlyItsBestCopy()
{
    UsenetQueueItem item;
    addFile(item, nzbFile(QStringLiteral("Rel.zip"), 8), fileState(8, parts(1, 8)));
    addFile(item, nzbFile(QStringLiteral("Rel.zip"), 8), fileState(8, {}));
    addPar2(item, QStringLiteral("Rel.vol0+1.par2"), 1);

    const UsenetRepairEstimate e = estimateRepair(item, kBlock, kRelSet);
    QCOMPARE(e.verdict, UsenetRepairEstimate::Verdict::Repairable);
    QCOMPARE(e.damagedBlocks, qint64(0));
}

void tst_UsenetReleaseChecks::aRepeatedPartNumberIsNotAHole()
{
    // Part 3 listed twice; one copy arrived. Nothing is short, and with no
    // recovery data at all a hole would read as unrepairable.
    NzbFileInfo info = nzbFile(QStringLiteral("Rel.zip"), 8);
    info.segments.append({QStringLiteral("Rel.zip.3b@test"), 4200, 3});
    UsenetFileState st = fileState(8, {});
    st.done.resize(9);
    st.missing.resize(9);
    st.done.setBit(8);
    st.missing.setBit(8);
    st.missingSegments = 1;

    UsenetQueueItem item;
    addFile(item, info, st);

    const UsenetRepairEstimate e = estimateRepair(item, kBlock, kRelSet);
    QCOMPARE(e.verdict, UsenetRepairEstimate::Verdict::Repairable);
    QCOMPARE(e.damagedBlocks, qint64(0));
}

void tst_UsenetReleaseChecks::recoveryDataIsCountedWhateverItIsCalled()
{
    // An obfuscated post names its volumes nothing like ".vol0+6.par2". Counted
    // by name, this release would have no recovery data and be stopped.
    UsenetQueueItem item;
    addFile(item, nzbFile(QStringLiteral("Rel.zip"), 8), fileState(8, parts(1, 6)));
    addFile(item, nzbFile(QStringLiteral("8f3a9c1d2e4b.bin"), 3, 8000),
            fileState(3, {}, parts(1, 3)));

    const UsenetRepairEstimate e = estimateRepair(item, kBlock, kRelSet);
    QCOMPARE(e.verdict, UsenetRepairEstimate::Verdict::Repairable);
    QCOMPARE(e.damagedBlocks, qint64(5));
    QCOMPARE(e.recoveryBlocks, qint64(6));
}

void tst_UsenetReleaseChecks::nothingToJudgeFromIsUnknown()
{
    UsenetQueueItem item;
    addFile(item, nzbFile(QStringLiteral("Rel.zip"), 8), fileState(8, parts(1, 6)));

    QCOMPARE(estimateRepair(item, 0, kRelSet).verdict, UsenetRepairEstimate::Verdict::Unknown);
    QCOMPARE(estimateRepair(item, kBlock, {}).verdict, UsenetRepairEstimate::Verdict::Unknown);

    Par2SetFile other;
    other.fileName = QStringLiteral("Other.zip");
    other.size = 24000;
    QCOMPARE(estimateRepair(item, kBlock, {other}).verdict,
             UsenetRepairEstimate::Verdict::Unknown);

    // An NZB that does not say how big its articles are.
    UsenetQueueItem sizeless;
    addFile(sizeless, nzbFile(QStringLiteral("Rel.zip"), 8, 0), fileState(8, parts(1, 6)));
    QCOMPARE(estimateRepair(sizeless, kBlock, kRelSet).verdict,
             UsenetRepairEstimate::Verdict::Unknown);
}

QTEST_GUILESS_MAIN(tst_UsenetReleaseChecks)
#include "tst_UsenetReleaseChecks.moc"
