#!/bin/sh
# ---------------------------------------------------------------------------
# entrypoint.sh — configure and run the cache server (nginx + php-fpm).
#
# Environment (set by cachenet.py):
#   CACHE_API_KEY_ID   api key id, labels the chunk owner and its quota counter
#   CACHE_API_KEY      the secret the seeder authenticates its POSTs with
#   PUBLIC_BASE_URL    pinned into the 201 "url" field
# ---------------------------------------------------------------------------
set -e

CACHE_API_KEY_ID="${CACHE_API_KEY_ID:-cachenet}"
CACHE_API_KEY="${CACHE_API_KEY:-cachenet-dev-key}"
PUBLIC_BASE_URL="${PUBLIC_BASE_URL:-http://cache}"

# A local checkout mounted read-only at /app-src is copied rather than used in
# place: the app wants a config.php of its own next to index.php, and writing
# that into somebody's working tree would be rude.
if [ -d /app-src ]; then
    echo "[cache] Using the bind-mounted backend at /app-src"
    rm -rf /app
    mkdir -p /app
    cp -a /app-src/. /app/
fi

mkdir -p /data/storage /data/var
chown -R www-data:www-data /data

# Nothing is served until config.php exists — index.php falls back to the
# installer, which would answer every API call with an HTML page.
cat > /app/config.php <<EOF
<?php

declare(strict_types=1);

namespace EMule\\HttpCache;

// Generated by docker/httpcache/cache/entrypoint.sh — a throwaway lab config.
return [
    'apiKeys' => [
        '${CACHE_API_KEY_ID}' => [
            'secret' => '${CACHE_API_KEY}',
            'quotaBytesPerDay' => 0,
            'enabled' => true,
        ],
    ],

    'openUpload' => false,

    // Outside the app tree so a rebuild of the image keeps the chunks, and so a
    // bind-mounted backend checkout is never written into.
    'storageDir' => '/data/storage',
    'varDir' => '/data/var',

    'maxChunkSize' => 10485760,

    // The rig runs inside a Docker VM whose free space is not ours to reason
    // about; a floor here would turn into a mid-run 507 that looks like a bug.
    'minFreeBytes' => 0,

    'defaultTtl' => 21600,
    'maxTtl' => 86400,

    // Pinned, not derived from the request: every node must be handed a URL that
    // resolves on this bridge network, whatever Host the publisher happened to use.
    'publicBaseUrl' => '${PUBLIC_BASE_URL}',

    // A sweep on 1% of uploads is pointless when a run publishes a handful of
    // chunks and is torn down afterwards.
    'gcProbability' => 0.0,
];
EOF
chown www-data:www-data /app/config.php

mkdir -p /run/nginx

echo "[cache] Serving ${PUBLIC_BASE_URL} — key id '${CACHE_API_KEY_ID}', storage /data/storage"
php-fpm --daemonize
exec nginx -g 'daemon off;'
