#!/usr/bin/env python3
"""
Collect the web template's translation markers for lupdate.

Usage:
    scripts/extract_web_strings.py           # rewrite src/core/webserver/WebTemplateStrings.h
    scripts/extract_web_strings.py --check   # exit 1 when that header is stale

The template marks translatable text as {{Text}} (HTML) or {{js:Text}} (inside a
JS string literal). lupdate cannot read a .tmpl, so every marker's text is written
as a QT_TRANSLATE_NOOP into a header it does read. scripts/localize.sh runs this
before lupdate, and tst_WebServer fails when the checked-in header is stale.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "data" / "config" / "eMule.tmpl"
HEADER = ROOT / "src" / "core" / "webserver" / "WebTemplateStrings.h"
CONTEXT = "eMule::WebServer"  # kWebTranslationContext

# WebTemplateEngine's marker alternative, exactly.
MARKER = re.compile(r"\{\{(js:)?([^{}\r\n]+?)\}\}")


def cpp_literal(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(texts: list[str]) -> str:
    entries = "\n".join(
        f"    QT_TRANSLATE_NOOP({cpp_literal(CONTEXT)}, {cpp_literal(t)})," for t in texts
    )
    return f"""#pragma once

/// @file WebTemplateStrings.h
/// @brief Every translation marker in data/config/eMule.tmpl, for lupdate.
///
/// Generated by scripts/extract_web_strings.py -- do not edit. The web server
/// translates the markers while it renders; this list only tells lupdate they
/// exist. tst_WebServer fails when it is stale.

#include <QtGlobal>

namespace eMule {{

inline constexpr const char* kWebTemplateStrings[] = {{
{entries}
}};

}} // namespace eMule
"""


def main() -> int:
    text = TEMPLATE.read_text(encoding="utf-8")
    texts = sorted({m.group(2) for m in MARKER.finditer(text)})
    wanted = render(texts)

    if "--check" in sys.argv[1:]:
        current = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if current != wanted:
            print(f"  {HEADER.relative_to(ROOT)} is stale; run {Path(__file__).name}",
                  file=sys.stderr)
            return 1
        return 0

    HEADER.write_text(wanted, encoding="utf-8")
    print(f"  {len(texts)} template strings -> {HEADER.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
